apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: kube-home
  namespace: {{.Values.argocd.namespace}}
spec:
  destination:
    name: ''
    namespace: apps
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
  sources:
  - repoURL: 'http://{{.Values.chartmuseum.helm.name}}.{{.Values.chartmuseum.helm.namespace}}:8080/'
    chart: {{index .Version "kube-home" "helm" "name"}}
    targetRevision: {{index .Version "kube-home" "helm" "version"}}
    helm:
      valueFiles:
      - $values/kube-home/values.yaml
  - repoURL: 'http://{{.Values.gitea.helm.name}}-http.{{.Values.gitea.helm.namespace}}:3000/{{.Values.cluster.user}}/cluster-config.git'
    targetRevision: HEAD
    ref: values