loki:
  auth_enabled: false
  isDefault: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1
  persistence:
    size: {{.Values.loki.storage}}