apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress
  namespace: kube-system
spec:
  routes:
    - match: Host(`{{index .Values "traefik-ui" "ingress"}}.{{.Values.server.hostname | lower}}`)
      kind: Rule
      middlewares:
        - name: auth-proxy
          namespace: {{.Values.oauth2.helm.namespace}}
        - name: traefik-ingress-redirect
          namespace: kube-system
      services:
        - name: traefik-dashboard
          port: 9000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress-auth
  namespace: kube-system
spec:
  routes:
    - match: "Host(`{{index .Values "traefik-ui" "ingress"}}.{{.Values.server.hostname | lower}}`) && PathPrefix(`/oauth2/`)"
      kind: Rule
      services:
        - name: {{.Values.oauth2.helm.name}}-oauth2-proxy
          namespace: {{.Values.oauth2.helm.namespace}}
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-ingress-redirect
  namespace: kube-system
spec:
  redirectRegex:
    regex: "^http://([^/]+)/?$"
    replacement: http://${1}/dashboard/