---
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
  namespace: kube-system
type: kubernetes.io/basic-auth
stringData:
  username: {{.Values.cluster.user}}
  password: {{.Values.cluster.password}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: kube-system
spec:
  basicAuth:
    secret: secret-basic-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: kube-system
  annotations:
    spec/ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-basic-auth@kubernetescrd
spec:
  rules:
    - host: {{index .Values "traefik-ui" "ingress"}}.{{.Values.server.hostname | lower}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik-dashboard
                port:
                  number: 9000