auth:
  adminUser: {{.Values.cluster.user}}
  adminPassword: {{.Values.cluster.password}}

tls:
  enabled: true
  existingSecret: "keycloak-cert"
  usePem: true

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: {{.Values.keycloak.ingress}}.{{.Values.server.hostname | lower}}

service:
  type: NodePort
  nodePorts: 
    https: {{.Values.keycloak.port}}
    http: {{.Values.keycloak.http}}