apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
  namespace: {{.Values.prometheus.helm.namespace}}
type: kubernetes.io/basic-auth
stringData:
  username: {{.Values.cluster.user}}
  password: {{.Values.cluster.password}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: {{.Values.prometheus.helm.namespace}}
spec:
  basicAuth:
    secret: secret-basic-auth