---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress
spec:
  routes:
    - match: Host(`whoami.swk3s`)
      kind: Rule
      middlewares:
        - name: auth-proxy
          namespace: default
      services:
        - name: whoami
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-auth
spec:
  routes:
    - match: "Host(`whoami.swk3s`) && PathPrefix(`/oauth2/`)"
      kind: Rule
      services:
        - name: auth-oauth2-proxy
          port: 80
---