---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: http://auth.swk3s
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  routes:
    - kind: Rule
      match: Host(`whoami.swk3s`)
      middlewares:
        - name: traefik-forward-auth
          namespace: default
      services:
        - name: whoami
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth
spec:
  routes:
    - kind: Rule
      match: Host(`auth.swk3s`)
      services:
        - name: traefik-forward-auth
          port: 80