config:
  clientID: "oauth2-proxy"
  clientSecret: "DN0OCSRvCxuuFeJFWhad9Nfu5cVcjm4d"
  # Create a new secret with the following command
  # openssl rand -base64 32 | head -c 32 | base64
  cookieSecret: "bGFsZWlyOHhxZEw2ZTRiUmdjcGpKRzViNW80RGJhWUk="
  configFile: |-
    provider="keycloak-oidc"
    redirect_url="http://whoami.swk3s/oauth2/callback"
    oidc_issuer_url="http://keycloak.swk3s/realms/cluster"
    cookie_secure="false"
    email_domains=["*"]
    cookie_domains=["*"]
    insecure_oidc_allow_unverified_email="true"