---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: port-forward
spec:
  replicas: 1
  selector:
    matchLabels:
      app: port-forward
  template:
    metadata:
      labels:
        app: port-forward
    spec:
      containers:
      - name: port-forward
        image: marcnuri/port-forward:latest
        env:
        - name: REMOTE_HOST
          value: "192.168.120.6"
        - name: REMOTE_PORT
          value: "50000"
        - name: LOCAL_PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: port-forward
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: port-forward