env:
  open:
    # disable all routes prefixed with /api
    DISABLE_API: false
  secret:
    # username for basic http authentication
    BASIC_AUTH_USER: {{.Values.chartmuseum.user}}
    # password for basic http authentication
    BASIC_AUTH_PASS: {{.Values.chartmuseum.password}}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: {{.Values.chartmuseum.storage}}

## Ingress for load balancer
ingress:
  enabled: true
  hosts:
  - name: {{.Values.chartmuseum.ingress}}.{{.Values.server.hostname | lower}}
    path: /