apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-builder
  namespace: {{.Values.dev.namespace}}
secrets:
  - name: gitea-credentials
imagePullSecrets:
  - name: registry-credentials

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-builder-role
  namespace: {{.Values.dev.namespace}}
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns", "tasks", "pipelines"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates", "interceptors", "triggers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-builder-rolebinding
  namespace: {{.Values.dev.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-builder-role
subjects:
  - kind: ServiceAccount
    name: tekton-builder
    namespace: {{.Values.dev.namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-builder-clusterrole
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clusterinterceptors", "clustertriggerbindings"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-builder-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-builder-clusterrole
subjects:
  - kind: ServiceAccount
    name: tekton-builder
    namespace: {{.Values.dev.namespace}}