apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-pvc
  namespace: {{.Values.dev.namespace}}
spec:
  description: Cleanup PVC after pipeline completes
  workspaces:
    - name: output
      description: Workspace to clean up
  steps:
    - name: cleanup
      image: chainguard/busybox:latest
      securityContext:
        runAsUser: 0
      script: |
        #!/bin/sh
        echo "Cleaning up workspace at $(workspaces.output.path)"
        rm -rf $(workspaces.output.path)/*
        echo "Workspace cleanup completed"
