# Ingress
ingress:
  # Enable the ingress for the user interface.
  enabled: false
  # Fully qualified domain name of a network host.
  hosts:
  - {{.Values.athens.ingress}}.{{.Values.server.hostname | lower}}

storage:
  disk: 
   persistence:
    enabled: true