apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{.Values.oauth2.helm.name}}-ingress
  namespace: {{.Values.oauth2.helm.namespace}}
spec:
  routes:
  - kind: Rule
    match: Host(`{{.Values.oauth2.ingress}}.{{.Values.server.hostname | lower}}`)
    #middlewares:
    #- name: auth-proxy-headers
    #  namespace: {{.Values.oauth2.helm.namespace}}
    services:
    - name: {{.Values.oauth2.helm.name}}-oauth2-proxy
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-proxy
  namespace: {{.Values.oauth2.helm.namespace}}
spec:
  forwardAuth:
    address: http://{{.Values.oauth2.ingress}}.{{.Values.server.hostname | lower}}/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: auth-proxy-headers
#  namespace: {{.Values.oauth2.helm.namespace}}
#spec:
#  headers:
#    browserXssFilter: true
#    contentTypeNosniff: true
#    forceSTSHeader: true
#    frameDeny: true
#    sslRedirect: false
#    stsIncludeSubdomains: true
#    stsPreload: true
#    stsSeconds: 315360000