config:
  clientID: "oauth2-proxy"
  clientSecret: "__secret__"
  # Create a new secret with the following command
  # openssl rand -base64 32 | head -c 32 | base64
  cookieSecret: "__cookie__"
  configFile: |-
    provider = "oidc"
    oidc_issuer_url = "http://{{.Values.keycloak.ingress}}.{{.Values.server.hostname | lower}}/realms/cluster"
    ssl_insecure_skip_verify="true"
    scope="openid email profile groups"
    reverse_proxy = "true"
    cookie_secure = "false"
    email_domains = [ "*" ]
    upstreams = [ "static://202" ]
    silence_ping_logging = "true"
    insecure_oidc_allow_unverified_email = "true"