---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2
  namespace: tekton-pipelines
spec:
  forwardAuth:
    address: http://oauth2-proxy.tekton-pipelines/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
  annotations:
    spec/ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.middlewares: tekton-pipelines-oauth2@kubernetescrd
spec:
  rules:
  - host: {{.Values.tekton.ingress}}.{{.Values.server.hostname | lower}}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: tekton-dashboard
            port:
              number: 9097